### ISSUE TITLE
Add in slackin

### ISSUE THREAD

**Issue by TJkrusinski** [TJkrusinski/orlando-developers#3]
see the repo: https://github.com/rauchg/slackin

I'm not sold on it, but it could help lower the barrier of entry.

**Comment by TJkrusinski** [comment]
After reading the blog post about slackin, http://rauchg.com/slackin/, it'd be great to integrate it into the site.

**Comment by dansackett** [comment]
Was starting to work on this but the package.json has a typo so can't be npm installed right now. There's a pull request in to fix it so maybe tomorrow it can be done correctly.

**Comment by TJkrusinski** [comment]
@dansackett hmmm, I don't see a typo in the json of package.json currently, can you fetch `origin/master` and try again?

**Comment by TJkrusinski** [comment]
Since we implemented the slash command we're gonna hold off on slackin for now. Gonna remove the labels.
