### ISSUE TITLE
Add in `/invite foo@email.com` slash command

### ISSUE THREAD

**Issue by TJkrusinski** [TJkrusinski/orlando-developers#8]
This has many benefits:
#### Exclusivity implications

I think we are all in accord that the nature of the slack group _not_ being entirely public is valuable. This gives members the opportunity to engage more comfortably as the conversation within the group is not public. Also, a CoC is more enforceable in a closed environment, which is not to say that we need absolute control of what is said, but rather so that those who are negatively impacting the group have recourse for their actions. Also, empowering preexisting members with the ability to invite potential members ad hoc drives community growth in a safe and scalable manner. Moreover, not having to combat spam bots, script kiddies (while unlikely) is a benefit.
#### Implementation details

Slack allows for custom 'slash commands' which are configurable to route out to an outgoing web hook. that is, `/invite foo@emai.com` would route to an outgoing web hook integration that performs the invite procedure for that new user.

Effectively:
- existing user runs `/invite name@email.com`
- webhook carries message payload to http server (our existing heroku server, which is running this repo)
- now we can diverge down two paths
  - web server sends email to a list of predefined admins (that are defined via env vars on heroku) with the message payload (this is the simple path, likely leaning towards this), then the admin has the ability to screen the user and send the invite
  - we use the slack api to automate the invitation of the email that was in the message payload

The automated route lends itself to being more complex, as there are more moving parts, also effectively makes the group public by way of anyone being able to immediately add anyone.
#### Pros
- Easier addition of new users! (yay)
- Enables the community to feel responsible for the members of the group
- Allows the group to grow more quickly
- Reduces strain of adding new users from admins
#### Cons
- Technical complexity
- Admins still need to manually add people going the non-automate route
- Potential for trolls to invite more trolls via automated route

Thoughts, concerns, questions?

**Comment by TJkrusinski** [comment]
Also worth noting that we seem to be in collective agreement that we are against letting recruiters into the group to keep it genuine. A screening process of some kind does a great job of preventing that.

**Comment by mattrw89** [comment]
Totally onboard with screening out people who are just recruiters.

A screening process would be great. Maybe you could make three commands...

1) /invite an_email_address -- this allows anyone to propose inviting someone

2) /lookupinvites -- this can only be run by an admin. This allows an admin to look at all current invitees.

3) /processinvite an_email_address -- this would actually invite them and could only be run by an admin. Maybe you could also pass ALL as an argument that would process all of them

Maybe also be neat for someone to add a short description of the person being invited with the /invite command.

**Comment by mattrw89** [comment]
Just remembered that you'll also need a /denyinvite command to get rid of the invite.

May make sense to back this with postgresql. Would only need a table I would think.

table: invites
cols:
ID  
CREATED_AT (timestamp w/o TZ)
EMAIL_ADDRESS    (string)
INVITED_BY     (string)
DESCRIPTION    (string)
RESPONDED_BY    (string)
RESPONDED_AT (timestamp w/o TZ)
RESPONSE (boolean)

I think that would be all we need.

**Comment by TJkrusinski** [comment]
@mattrw89 I dig the ambition but I think it's in our best interest to just be as simple as possible.

Thinking about this more I think we should just relay messages from `/invite foo` to a private group with admins in it to be as simple as possible.

**Comment by mattrw89** [comment]
That'll work just fine too. Admin's will probably want to put in there that they processed emails x,y,z in order to know that everyone has been invited.
